### ISSUE TITLE
PWM only produces max frequency of 1.8khz

### ISSUE THREAD

**Issue by bmentink** [tinygo-org/tinygo#2592]
No matter what value I give "period" in the code below, I can't get a higher PWM on the pin of 1.8Khz.

Save the following file as main.go....
[main.txt](https://github.com/tinygo-org/tinygo/files/7962672/main.txt)

**Comment by soypat** [comment]
What version of tinygo are you running? 

Edit: There's been some changes to the Pico's PWM in the last couple versions. Specifically https://github.com/tinygo-org/tinygo/pull/2230 fixed a bug in it and was released in v0.21.  If you can please show us the result of `pwm.Period()`

**Comment by soypat** [comment]
Nevermind, found the bug. Forgot to add a check if `whole` was zero [here](https://github.com/tinygo-org/tinygo/blob/release/src/machine/machine_rp2040_pwm.go#L281) as a result of the division, in which case the `top` calculation fails. In this case `whole` should be set to 1, that should fix it. Will PR a fix

**Comment by bmentink** [comment]
I am using version  0.21.0 of tinyGO. 

pwm.Period is 524288 .. (that is with period set to 100e3) actually next time I tried it was 622592

println("DIV=", pwm.DIV.Reg, "CTR=", pwm.CTR.Reg, "CSR=", pwm.CSR.Reg, "Period", pwm.Period()) results in:
DIV= 19 CTR= 3621 CSR= 1 Period 622592

@soypat  I can confirm that with some period values, I get a "divide by zero" error ...

Hope that helps ..

**Comment by bmentink** [comment]
Update: Tried V0.22 ... still can't increase my max frequency ... did the fix go into that build?

Also, I noticed that after the upgrade from 0.21 -> 0.22 that I had to run tinygo as root, normal user can no longer run due to permission issues, error below:

`tinygo flash -target=pico main.go 
tinygo:ld.lld: error: cannot open /usr/local/lib/tinygo/pkg/thumbv6m-unknown-unknown-eabi-cortex-m0plus/compiler-rt/lib.a: Permission denied
tinygo:ld.lld: error: cannot open /usr/local/lib/tinygo/pkg/thumbv6m-unknown-unknown-eabi-cortex-m0plus/picolibc/lib.a: Permission denied
failed to run tool: ld.lld
error: failed to link /tmp/tinygo2262361142/main: exit status 1`

**Comment by soypat** [comment]
The fix is still no part of TinyGo, it first needs to be merged. If you want the fix today you'd need to clone my TinyGo fork, switch to branch `rp2040-pwmfreqfix` and build TinyGo from source https://tinygo.org/docs/guides/build/

**Comment by bmentink** [comment]
No problem, will wait  till it's merged .. any idea's about the permission issues with tinyGo?

**Comment by dkegel-fastly** [comment]
The permissions thing is unrelated, possibly a packaging problem.

Please file a new bug with whoever built that tinygo (possibly this project, I dunno), and whether doing

sudo chmod 644 /usr/local/lib/tinygo/pkg/thumbv6m-unknown-unknown-eabi-cortex-m0plus/compiler-rt/lib.a

helps.

**Comment by bmentink** [comment]
@soypat 
Could you point me to your above branch with the fix for PWM freq? I can't see your branch listed in the available branches to checkout:

`git checkout rp2040-pwmfreqfix
error: pathspec 'rp2040-pwmfreqfix' did not match any file(s) known to git
`

**Comment by dkegel-fastly** [comment]
It's in his fork, https://github.com/soypat/tinygo/tree/rp2040-pwmfreqfix

Try
```
git remote add soypat https://github.com/soypat/tinygo
git fetch soypat
git checkout rp2040-pwmfreqfix
```

**Comment by bmentink** [comment]
Cool, building now ..

**Comment by bmentink** [comment]
@soypat 
Seemed to build ok and version is:
`tinygo version 0.23.0-dev-e952fc92 linux/amd64 (using go version go1.17.6 and LLVM version 13.0.0)`

However, I get the following when I compile the project:

`./build/tinygo flash -target=pico main.go 
../.cache/tinygo/goroot-647906ad3368d070a4d452794afa8fe948e67ff2737de7db58dc5a365e299fc5/src/machine/machine_rp2040.go:7:2: package device/rp is not in GOROOT (/home/bmentink/.cache/tinygo/goroot-647906ad3368d070a4d452794afa8fe948e67ff2737de7db58dc5a365e299fc5/src/device/rp)
`

Makes no difference deleting the .cache directory, or if I run it as chroot or not ... 


EDIT: oops, missed a step, doing `make gen-device` now ;)

**Comment by bmentink** [comment]
Next error is:

`./build/tinygo flash -target=pico main.go 
# os/user
../../../usr/local/go/src/os/user/cgo_lookup_unix.go:21:6: not implemented: build constraints in #cgo line
../../../usr/local/go/src/os/user/getgrouplist_unix.go:18:9: error: implicit declaration of function 'getgrouplist' is invalid in C99
`

Is my version of go correct?  `go version go1.17.6 linux/amd64`

**Comment by bmentink** [comment]
ahhh, needs to be executed in the project directory ..

All good now, I have a PWM at the programmed 30Khz .. many thanks.

EDIT: Question, Top=4165 now instead of 4096, is this correct? (Period= 1e9 / 30e3)
